
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author angeles
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //Boton.setBackground(0,0,0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Autor = new javax.swing.JLabel();
        LabelRed = new javax.swing.JLabel();
        LabelGreen = new javax.swing.JLabel();
        LabelBlue = new javax.swing.JLabel();
        SliderRed = new javax.swing.JSlider();
        SliderGreen = new javax.swing.JSlider();
        SliderBlue = new javax.swing.JSlider();
        TextoRed = new javax.swing.JTextField();
        TextoGreen = new javax.swing.JTextField();
        TextoBlue = new javax.swing.JTextField();
        BarraRed = new javax.swing.JProgressBar();
        BarraGreen = new javax.swing.JProgressBar();
        BarraBlue = new javax.swing.JProgressBar();
        Boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monitorizar Eventos");
        setResizable(false);

        Autor.setText("Hecho por Ángeles Fuentes Expósito para DIU");

        LabelRed.setForeground(new java.awt.Color(255, 0, 51));
        LabelRed.setText("R:");

        LabelGreen.setForeground(new java.awt.Color(0, 204, 51));
        LabelGreen.setText("G:");

        LabelBlue.setForeground(new java.awt.Color(0, 0, 204));
        LabelBlue.setText("B:");

        SliderRed.setMajorTickSpacing(50);
        SliderRed.setMaximum(255);
        SliderRed.setValue(0);
        SliderRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderRedStateChanged(evt);
            }
        });
        SliderRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SliderRedMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SliderRedMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SliderRedMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SliderRedMouseEntered(evt);
            }
        });

        SliderGreen.setMajorTickSpacing(50);
        SliderGreen.setMaximum(255);
        SliderGreen.setValue(0);
        SliderGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderGreenStateChanged(evt);
            }
        });

        SliderBlue.setMajorTickSpacing(50);
        SliderBlue.setMaximum(255);
        SliderBlue.setValue(0);
        SliderBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderBlueStateChanged(evt);
            }
        });

        TextoRed.setText("0");
        TextoRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoRedActionPerformed(evt);
            }
        });

        TextoGreen.setText("0");
        TextoGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoGreenActionPerformed(evt);
            }
        });

        TextoBlue.setText("0");
        TextoBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoBlueActionPerformed(evt);
            }
        });

        BarraRed.setForeground(new java.awt.Color(153, 0, 0));
        BarraRed.setMaximum(255);

        BarraGreen.setMaximum(255);

        BarraBlue.setMaximum(255);

        Boton.setBackground(new java.awt.Color(0, 0, 0));
        Boton.setForeground(new java.awt.Color(0, 0, 0));
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Autor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(LabelRed)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelGreen, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelBlue, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SliderRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextoRed, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SliderGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BarraGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SliderBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BarraBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextoBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BarraRed, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SliderRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelRed))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(BarraRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SliderGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelGreen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BarraGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(TextoGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LabelBlue)
                                .addComponent(SliderBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BarraBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Autor)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoGreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoGreenActionPerformed

    private void TextoBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoBlueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoBlueActionPerformed

    private void TextoRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoRedActionPerformed

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActionPerformed

    private void SliderRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderRedStateChanged
        // TODO add your handling code here:
        cambiarColor();

    }//GEN-LAST:event_SliderRedStateChanged

    private void SliderGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderGreenStateChanged
        cambiarColor();
    }//GEN-LAST:event_SliderGreenStateChanged

    private void SliderBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderBlueStateChanged
        cambiarColor() ;
    }//GEN-LAST:event_SliderBlueStateChanged

    private void SliderRedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderRedMouseEntered
        Boton.setText("Dentro");
    }//GEN-LAST:event_SliderRedMouseEntered

    private void SliderRedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderRedMouseExited
        Boton.setText("Fuera");
    }//GEN-LAST:event_SliderRedMouseExited

    private void SliderRedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderRedMousePressed
        Boton.setText("Presionado");

    }//GEN-LAST:event_SliderRedMousePressed

    private void SliderRedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderRedMouseReleased
        Boton.setText("Liberado");
    }//GEN-LAST:event_SliderRedMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JProgressBar BarraBlue;
    private javax.swing.JProgressBar BarraGreen;
    private javax.swing.JProgressBar BarraRed;
    private javax.swing.JButton Boton;
    private javax.swing.JLabel LabelBlue;
    private javax.swing.JLabel LabelGreen;
    private javax.swing.JLabel LabelRed;
    private javax.swing.JSlider SliderBlue;
    private javax.swing.JSlider SliderGreen;
    private javax.swing.JSlider SliderRed;
    private javax.swing.JTextField TextoBlue;
    private javax.swing.JTextField TextoGreen;
    private javax.swing.JTextField TextoRed;
    // End of variables declaration//GEN-END:variables

    private void cambiarColor() {
        int valorR = SliderRed.getValue();
        int valorG= SliderGreen.getValue();
        int valorB = SliderBlue.getValue();
        BarraRed.setValue(valorR);
        TextoRed.setText(String.valueOf(valorR));
        BarraGreen.setValue(valorG);
        TextoGreen.setText(String.valueOf(valorG));
        BarraBlue.setValue(valorB);
        TextoBlue.setText(String.valueOf(valorB));
        
        Color color = new Color (valorR,valorG,valorB);
        Boton.setBackground(color);
    }


}
